#!/usr/bin/python3
from failover import *
import sys

main(sys.argv[1:])
